//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

@class TDTemplateRenderingMode, TDThemeBitSource;

@interface TDAsset : NSManagedObject
{
    unsigned int _scaleFactor;
}

+ (long long)subtypeFromImageFilename:(id)arg1;
+ (long long)idiomFromImageFilename:(id)arg1;
+ (BOOL)isTemplateFromImageFilename:(id)arg1;
+ (unsigned int)scaleFactorFromImageFilename:(id)arg1;
+ (id)_filenameRegex;
@property(readonly, nonatomic) NSString *baseName;
- (void)setHasProduction:(id)arg1;
- (BOOL)hasProduction;

- (NSURL *)fileURLWithDocument:(CoreThemeDocument *)document;

- (id)sourceRelativePath;
- (id)_sourceRelativePathComponents;
- (unsigned int)scaleFactor;
- (void)setScaleFactor:(unsigned int)arg1;

// Remaining properties
@property(retain, nonatomic) NSString *category; // @dynamic category;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) TDThemeBitSource *source; // @dynamic source;
@property(retain, nonatomic) TDTemplateRenderingMode *templateRenderingMode; // @dynamic templateRenderingMode;

@end

