//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TDRenditionSpec.h"

@class NSImage, NSNumber, NSSet;

@interface TDEffectRenditionSpec : TDRenditionSpec
{
    NSImage *_sampleImage;
}

- (BOOL)canBePackedWithDocument:(id)arg1;
- (id)createCSIRepresentationWithCompression:(BOOL)arg1 colorSpaceID:(unsigned long long)arg2 document:(id)arg3;
- (id)effectPreset;
- (void)setComponentsFromEffectPreset:(id)arg1 withDocument:(id)arg2;
- (void)dealloc;
- (NSImage *)sampleImage;
- (struct CGImage *)_effectSampleImage;

// Remaining properties
@property(retain, nonatomic) NSSet *components; // @dynamic components;
@property(retain, nonatomic) NSNumber *effectScale; // @dynamic effectScale;

@end

