//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  7 2015 21:36:47).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@import Cocoa;

@class NSNumber, TDEffectComponent, TDEffectParameterType;

@interface TDEffectParameterValue : NSManagedObject

@property(retain, nonatomic) NSNumber *angleValue; // @dynamic angleValue;
@property(retain, nonatomic) NSNumber *colorValue; // @dynamic colorValue;
@property(retain, nonatomic) TDEffectComponent *component; // @dynamic component;
@property(retain, nonatomic) NSNumber *floatValue; // @dynamic floatValue;
@property(retain, nonatomic) NSNumber *intValue; // @dynamic intValue;
@property(retain, nonatomic) TDEffectParameterType *parameterType; // @dynamic parameterType;

@end

